#!/bin/sh

### Start dbus ###
if test -z "$DBUS_SESSION_BUS_ADDRESS"; then
    eval `dbus-launch --sh-syntax --exit-with-session`
fi


### Start programs ###
sxhkd &
compton &
$HOME/.config/polybar/launch.sh &
#yabar &
#tint2 &
start-pulseaudio-x11
#stalonetray -c $HOME/.config/stalonetrayrc &
nm-applet &
#pa-applet &
#yabar

light-locker \
    --lock-on-suspend \
    --lock-on-lid \
    --idle-hint \
    --lock-after-screensaver=5 \
    --idle-hint &

### Enable natural scrolling ###

# Get touchpad id
#ID=$(xinput list | grep -Eio '(touchpad|glidepoint)\s*id\=[0-9]{1,2}' | -Eo '[0-9]{1,2}')

# Set property
#xinput set-prop $ID "libinput Natural Scrolling Enabled" 1


# Rename so java will work
wmname LG3D

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         4
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

