#!/bin/sh

### Start dbus ###
if test -z "$DBUS_SESSION_BUS_ADDRESS"; then
    eval $(dbus-launch --sh-syntax --exit-with-x11)
    export DBUS_SESSION_BUS_PID
fi

export SXHKD_SHELL=/bin/sh

### Start gnome-keyring-daemon ###
eval $(gnome-keyring-daemon --start)
export SSH_AUTH_SOCK

### Start programs ###
sxhkd &
compton &
dunst &
$HOME/.config/polybar/launch.sh &
start-pulseaudio-x11
nm-applet &
/usr/libexec/xfce-polkit &

TEXT_COLOR=ffffffff
xss-lock -- i3lock \
	--blur=10 \
	--indicator --clock \
	--verifcolor=$TEXT_COLOR \
	--wrongcolor=$TEXT_COLOR \
	--layoutcolor=$TEXT_COLOR \
	--datecolor=$TEXT_COLOR \
    --timecolor=$TEXT_COLOR &


### Enable natural scrolling ###

# Get touchpad id
#ID=$(xinput list | grep -Eio '(touchpad|glidepoint)\s*id\=[0-9]{1,2}' | -Eo '[0-9]{1,2}')

# Set property
#xinput set-prop $ID "libinput Natural Scrolling Enabled" 1


# Rename so java will work
wmname LG3D

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         4
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a zathura state=tiled

# Because Libreoffice is horrible
bspc rule -a libreoffice state=tiled
bspc rule -a Soffice state=tiled
bspc rule -a libreoffice-base state=tiled
bspc rule -a libreoffice-basic state=tiled
bspc rule -a libreoffice-calc state=tiled
bspc rule -a libreoffice-draw state=tiled
bspc rule -a libreoffice-impress state=tiled
bspc rule -a libreoffice-math state=tiled
bspc rule -a libreoffice-writer state=tiled
